"""create ledger feature tables

Revision ID: cffdb6f0810c
Revises: 
Create Date: 2026-07-26 18:52:40.391652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cffdb6f0810c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_currency', sa.Enum('EUR', 'USD', name='currency'), nullable=False),
    sa.Column('quote_currency', sa.Enum('EUR', 'USD', name='currency'), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_guild_config',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_role_ids', sa.JSON(), nullable=False),
    sa.Column('user_role_ids', sa.JSON(), nullable=False),
    sa.Column('ledger_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('audit_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.Enum('EUR', 'USD', name='currency'), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('ledger_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='transactiontype'), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.Enum('EUR', 'USD', name='currency'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'KOFI', name='transactionsource'), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', 'CORRECTED', name='transactionstatus'), nullable=False),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_message_id', sa.BigInteger(), nullable=True),
    sa.Column('correction_of_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['correction_of_id'], ['ledger_transactions.id'], ),
    sa.ForeignKeyConstraint(['guild_id'], ['ledger_guild_config.guild_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_transactions_guild_id'), ['guild_id'], unique=False)

    op.create_table('ledger_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_audit_log_guild_id'), ['guild_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_audit_log_guild_id'))

    op.drop_table('ledger_audit_log')
    with op.batch_alter_table('ledger_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_transactions_guild_id'))

    op.drop_table('ledger_transactions')
    op.drop_table('ledger_guild_config')
    op.drop_table('ledger_exchange_rates')
    # ### end Alembic commands ###
